/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab8p2_luisvarela;

import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Andres Varela
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        iniciar_crear.setVisible(false);
        pbar_iniciar.setVisible(false);
        usuario.setVisible(false);
        admin.setVisible(true);
        adminjugador j = new adminjugador("./Usuario.usr");
        j.getlistajugador().add(new jugador("a", "a", "a", new Date(), "a", "a"));
        j.getlistajugador().add(new jugador("a", "a", "a", new Date(), "s", "s"));
        j.getlistajugador().add(new jugador("a", "a", "a", new Date(), "d", "d"));
        j.getlistajugador().add(new jugador("a", "a", "a", new Date(), "f", "f"));
        i_barra.setStringPainted(true);
        j.escribirArchivo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JPanel();
        iniciar_crear = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        i_usuario = new javax.swing.JTextField();
        i_contrasena = new javax.swing.JTextField();
        Listo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();
        Pais = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        pbar_iniciar = new javax.swing.JPanel();
        i_barra = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        admin = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        concesionaria_locacion = new javax.swing.JTextField();
        concesionaria_nombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        longitud = new javax.swing.JTextField();
        curvas = new javax.swing.JTextField();
        locacion = new javax.swing.JTextField();
        tipo_carrera = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        modelo_c = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_concesionaria = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        marca_c = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        carro_color = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        precio_carro = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        year = new com.toedter.calendar.JYearChooser();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        velocidad_punta = new javax.swing.JTextField();
        reconstruido = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        pais_c = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cb_tiempo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        caballero_fuerza1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuario.setMinimumSize(new java.awt.Dimension(790, 540));
        usuario.setPreferredSize(new java.awt.Dimension(790, 540));
        usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar_crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Iniciar Sesion");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        Listo.setText("listo");
        Listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Listo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(i_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(i_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(Listo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Iniciar Sesion", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha de nacimiento:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Correo:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 20));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Pais de residencia:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, 20));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Registro");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 30));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Usuario:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, 20));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 710, 10));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 20));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel6.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 220, -1));

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jPanel6.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 220, -1));

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        jPanel6.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 220, -1));

        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });
        jPanel6.add(Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, -1));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel6.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, -1));

        jButton2.setText("Listo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 150, -1));
        jPanel6.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 190, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Registro", jPanel4);

        iniciar_crear.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 510));

        pbar_iniciar.setMinimumSize(new java.awt.Dimension(790, 540));
        pbar_iniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i_barra.setToolTipText("");
        pbar_iniciar.add(i_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 570, 45));

        jLabel4.setText("Buscando Usuario");
        pbar_iniciar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, -1));

        admin.setMinimumSize(new java.awt.Dimension(790, 540));
        admin.setPreferredSize(new java.awt.Dimension(790, 540));
        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Nombre");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel17.setText("locacion");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jButton4.setText("listo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 96, -1));
        jPanel3.add(concesionaria_locacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 88, -1));
        jPanel3.add(concesionaria_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 88, -1));

        jTabbedPane2.addTab("Agregar concesionaria", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Longitud");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 75, -1, -1));

        jLabel6.setText("Cantidad de curvas ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 112, -1, -1));

        jLabel7.setText(" Tipo de carreras");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 149, -1, -1));

        jLabel15.setText("Locacion");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 182, -1, -1));

        jButton3.setText("listo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 277, 96, -1));
        jPanel5.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 73, 88, -1));
        jPanel5.add(curvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 110, 88, -1));
        jPanel5.add(locacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 180, 88, -1));
        jPanel5.add(tipo_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 147, 88, -1));

        jTabbedPane2.addTab("Agregar circuito", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(modelo_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 32));

        jLabel18.setText("Velocidad_Punta");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 90, 10));

        jLabel19.setText("Pais");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 30, -1));

        jPanel1.add(cb_concesionaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 150, 32));

        jLabel20.setText("Marca");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, 10));

        marca_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marca_cMouseClicked(evt);
            }
        });
        jPanel1.add(marca_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 32));

        jLabel21.setText("Modelo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 40, 10));

        carro_color.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout carro_colorLayout = new javax.swing.GroupLayout(carro_color);
        carro_color.setLayout(carro_colorLayout);
        carro_colorLayout.setHorizontalGroup(
            carro_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        carro_colorLayout.setVerticalGroup(
            carro_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(carro_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 30));

        jLabel22.setText("Color");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 40, 10));
        jPanel1.add(precio_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 150, 30));

        jLabel24.setText("Precio");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 10));

        year.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 90, 30));

        jLabel25.setText("reconstruido");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 70, 10));

        jLabel26.setText("Horsepower");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 70, 10));
        jPanel1.add(velocidad_punta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, 30));

        reconstruido.setText("si o no");
        jPanel1.add(reconstruido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 100, 30));

        jLabel27.setText("Concesionaria");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        pais_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "Alemania", "Japon", "Italia" }));
        pais_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pais_cMouseClicked(evt);
            }
        });
        jPanel1.add(pais_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 32));

        jButton5.setText("listo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, 50));

        jLabel28.setText("Tiempo");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        cb_tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 a 60 km/h ", "0 a 100 km/h" }));
        jPanel1.add(cb_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, 32));

        jLabel29.setText(" Año de fabricación");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, 10));
        jPanel1.add(caballero_fuerza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 30));

        jTabbedPane2.addTab("Agregar carro", jPanel1);

        admin.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 780, 430));

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        admin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciar_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pbar_iniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciar_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pbar_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (nombre.getText() != null && Correo.getText() != null && Pais.getText() != null && Usuario.getText() != null && Contrasena.getText() != null) {
            boolean cumple_edad = validacion_fecha();
            if (cumple_edad) {
                boolean nombre_usuario = validacion_nombre_usuario_mismo_nombre();
                if (nombre_usuario) {
                    boolean contasena_no_valida = validando_nombre_contasena_2();
                    if (contasena_no_valida) {
                        adminjugador j = new adminjugador("./Usuario.usr");
                        j.getlistajugador().add(new jugador(nombre.getText(), Correo.getText(), Pais.getText(), fecha.getDate(), Usuario.getText(), Contrasena.getText()));
                        j.escribirArchivo();
                        nombre.setText("");
                        Correo.setText("");
                        Pais.setText("");
                        fecha.setDate(new Date());
                        Usuario.setText("");
                        Contrasena.setText("");

                        JOptionPane.showMessageDialog(this, "Se a registrado exitosamente");
                    } else {
                        JOptionPane.showMessageDialog(this, "Esta contraseña no es valida porque debe de:\nContener mínimo una letra mayúscula \nUna minúscula\nUn arácter especial");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Este nombre de usuario ya fue tomado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Es menor de edad");
                nombre.setText("");
                Usuario.setText("");
                Contrasena.setText("");
                Correo.setText("");
                Pais.setText("");
                fecha.setDate(new Date());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void ListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoActionPerformed
        if (i_usuario.getText().equals("admin") && i_contrasena.getText().equals("admin")) {
            admin.setVisible(true);
            iniciar_crear.setVisible(false);
        } else if (i_usuario.getText() != null && i_contrasena.getText() != null) {
            hilo_inciar h_i = new hilo_inciar(i_barra, pbar_iniciar, usuario, iniciar_crear);
            adminjugador j = new adminjugador("./Usuario.usr");
            j.cargarArchivo();
            boolean usuario_no_encontrado = true;
            for (jugador object : j.getlistajugador()) {
                if (i_usuario.getText().equals(object.getUsuario()) && i_contrasena.getText().equals(object.getContrasena())) {
                    i_barra.setMaximum((j.getlistajugador().indexOf(object) + 1));
                    usuario_no_encontrado = false;
                    break;
                }
            }
            i_barra.setMinimum(0);
            iniciar_crear.setVisible(false);
            pbar_iniciar.setVisible(true);
            h_i.start();

            if (i_usuario.getText().equals("admin") && i_contrasena.getText().equals("admin")) {

            }
        } else {

        }
    }//GEN-LAST:event_ListoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        admin.setVisible(false);
        iniciar_crear.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (concesionaria_locacion.getText() != null && concesionaria_nombre.getText() != null) {
            concesionarias temp = new concesionarias(concesionaria_nombre.getText(), concesionaria_locacion.getText());
            adminConcesionarias c = new adminConcesionarias("./Concesionaria.cns");
            c.agregar_concesionaria(temp);
            c.escribirArchivo();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        adminConcesionarias c = new adminConcesionarias("./Concesionaria.cns");
        c.cargarArchivo();
        cb_concesionaria.removeAll();
        if (!c.getListaConcesionaria().isEmpty()) {
            for (concesionarias object : c.getListaConcesionaria()) {
                cb_concesionaria.addItem(object.getNombre());
            }
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void pais_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pais_cMouseClicked
        String pais = (String) pais_c.getSelectedItem();
        marca_c.removeAllItems();

        switch (pais) {
            case "Japon":
                marca_c.addItem("Subaru");
                marca_c.addItem("Toyota");
                marca_c.addItem("Honda");
                marca_c.addItem("Mitsubishi");
                marca_c.addItem("Nissan");
                break;
            case "Italia":
                marca_c.addItem("Ferrari");
                marca_c.addItem("Lamborghini");
                break;
            case "USA":
                marca_c.addItem("Ford");
                marca_c.addItem("Chevrolet");
                marca_c.addItem("Acorh");
                break;
            case "Alemania":
                marca_c.addItem("BWW");
                marca_c.addItem("Mercedes-Benz");
                marca_c.addItem("VW");
                marca_c.addItem("Audi");
                marca_c.addItem("Porsche");
                break;
            default:
                System.out.println("Valor inesperado de país: " + pais);

                throw new AssertionError();
        }
    }//GEN-LAST:event_pais_cMouseClicked

    private void marca_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marca_cMouseClicked
        String marca = (String) marca_c.getSelectedItem();
        modelo_c.removeAllItems();

        switch (marca) {
            case "Subaru" -> {
                modelo_c.addItem("BRZ");
                modelo_c.addItem("Impreza");
                modelo_c.addItem("WPZ-X");
            }
            case "Toyota" -> {
                modelo_c.addItem("GT-86");
                modelo_c.addItem("Supra");
            }
            case "Honda" -> {
                modelo_c.addItem("Civic Type-R");
                modelo_c.addItem("Integra Type-K");
                modelo_c.addItem("CR-X");
            }
            case "Nissan" -> {
                modelo_c.addItem("Skyline-GTR34");
                modelo_c.addItem("Skyline-GTR32");
                modelo_c.addItem("GTR-R35");
            }
            case "Ferrari" -> {
                modelo_c.addItem("LaFerrari");
                modelo_c.addItem("Testorroso");
                modelo_c.addItem("240");

            }
            case "Lamborghini" -> {
                modelo_c.addItem("Diablo");
                modelo_c.addItem("Huracan");
                modelo_c.addItem("Murcielago");
            }
            case "Ford" -> {
                modelo_c.addItem("Mustang");
                modelo_c.addItem("F-150");
            }
            case "Chevrolet" -> {
                modelo_c.addItem("Camaro");
                modelo_c.addItem("Bel-Hir");
            }

            case "Acorh" -> {
                modelo_c.addItem("NSX");
            }
            case "BWW" -> {
                modelo_c.addItem("M3");
                modelo_c.addItem("X6");
                modelo_c.addItem("M5");
            }
            case "Mercedes-Benz" -> {
                modelo_c.addItem("Clase A");
                modelo_c.addItem("GLA");
                modelo_c.addItem("GLC");
                modelo_c.addItem("GLS");
            }

            case "VW" -> {
                modelo_c.addItem("Beetle");
            }
            case "Audi" -> {
                modelo_c.addItem("RB");
                modelo_c.addItem("T-Coupe");
            }
            case "Porsche" -> {
                modelo_c.addItem("All Carrera");
                modelo_c.addItem("978");
            }
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_marca_cMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        Color color = JColorChooser.showDialog(this, "Color del carro", Color.yellow);
        carro_color.setBackground(color);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        adminCarro ca = new adminCarro("./Carros.car");
        adminConcesionarias c = new adminConcesionarias("./Concesionaria.cns");
        boolean recontruido_b = false;
        if (reconstruido.getText().equalsIgnoreCase("si")) {
            recontruido_b = true;
        } else {
            recontruido_b = false;
        }
        int temp1 = 0;
        if (cb_tiempo.getSelectedIndex() == 0) {
            temp1 = 60;
        } else {
            temp1 = 100;
        }

        carro temp = new carro(recontruido_b, (String) marca_c.getSelectedItem(), (String) modelo_c.getSelectedItem(), carro_color.getBackground(), Integer.parseInt(precio_carro.getText()), (String) pais_c.getSelectedItem(), year.getYear(), Integer.parseInt(caballero_fuerza1.getText()), Integer.parseInt(velocidad_punta.getText()), temp1);
        for (concesionarias object : c.getListaConcesionaria()) {
            if (object.getNombre().equals((String) cb_concesionaria.getSelectedItem())) {
                c.getListaConcesionaria().get(c.getListaConcesionaria().indexOf(object)).getC().add(temp);
            }

        }
        ca.getLista().add(temp);
        ca.escribirArchivo();
        c.escribirArchivo();
    }//GEN-LAST:event_jButton5ActionPerformed
    public boolean validacion_nombre_usuario_mismo_nombre() {
        adminjugador j = new adminjugador("./Usuario.usr");
        for (jugador object : j.getlistajugador()) {
            if (object.getUsuario().equals(Usuario.getText())) {
                return false;
            }
        }
        return true;
    }

    public boolean validando_nombre_contasena_2() {
        String c = Contrasena.getText();
        int mayuscula = 0;
        int minuscula = 0;
        int especial = 0;
        for (int i = 0; i < c.length(); i++) {
            char letra = c.charAt(i);
            if ((int) letra >= 97 && (int) letra <= 122) {
                minuscula++;
            }
            if ((int) letra >= 65 && (int) letra <= 90) {
                mayuscula++;
            }
            if ((int) letra >= 33 && (int) letra <= 47) {
                especial++;
            }
            if ((int) letra >= 58 && (int) letra <= 64) {
                especial++;
            }
        }
        if (mayuscula == 0 || minuscula == 0 || especial == 0) {
            return false;
        } else {
            return true;
        }
    }

    public boolean validacion_fecha() {
        Date nacimiento = fecha.getDate();
        int year = nacimiento.getYear() + 1900, dia = nacimiento.getDay(), mes = nacimiento.getMonth() + 1;
        Date hoy = new Date();
        int year1 = hoy.getYear() + 1900, dia1 = hoy.getDay(), mes1 = hoy.getMonth() + 1, diferencia = 0;
        diferencia = year1 - year;
        if (mes1 >= mes) {
            if (dia1 >= dia && mes1 == mes) {
            } else if (mes1 == mes) {
                diferencia--;
            }
        } else {
            diferencia--;
        }
        if (diferencia <= 12) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField Correo;
    private javax.swing.JButton Listo;
    private javax.swing.JTextField Pais;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel admin;
    private javax.swing.JTextField caballero_fuerza1;
    private javax.swing.JPanel carro_color;
    private javax.swing.JComboBox<String> cb_concesionaria;
    private javax.swing.JComboBox<String> cb_tiempo;
    private javax.swing.JTextField concesionaria_locacion;
    private javax.swing.JTextField concesionaria_nombre;
    private javax.swing.JTextField curvas;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JProgressBar i_barra;
    private javax.swing.JTextField i_contrasena;
    private javax.swing.JTextField i_usuario;
    private javax.swing.JPanel iniciar_crear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField locacion;
    private javax.swing.JTextField longitud;
    private javax.swing.JComboBox<String> marca_c;
    private javax.swing.JComboBox<String> modelo_c;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pais_c;
    private javax.swing.JPanel pbar_iniciar;
    private javax.swing.JTextField precio_carro;
    private javax.swing.JTextField reconstruido;
    private javax.swing.JTextField tipo_carrera;
    private javax.swing.JPanel usuario;
    private javax.swing.JTextField velocidad_punta;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables
}
